### ISSUE TITLE
ASS File add support to XX:XX:XX.CS

### ISSUE THREAD

**Issue by oMarcinMazurek** [JDaren/subtitleConverter#22]
Sometimes some of Online converters(http://subtitleconverter.net/) wrong convert timestamp i know that should be X:XX:XX.CS but sometimes better is to prevent the exception so this is my changes 
			} else if (dialogueFormat[i].trim().equalsIgnoreCase("Start")){
				//we save the starting time
				try{
				newCaption.start=new Time("h:mm:ss.cs",line[i].trim());
				}catch(java.lang.NumberFormatException exception){
					newCaption.start=new Time("hh:mm:ss.cs",line[i].trim());
				}
			} else if (dialogueFormat[i].trim().equalsIgnoreCase("End")){
				try{
				//we save the starting time
					newCaption.end=new Time("h:mm:ss.cs",line[i].trim());
				}catch(java.lang.NumberFormatException exception){
					newCaption.end=new Time("hh:mm:ss.cs",line[i].trim());
				}

**Comment by JDaren** [comment]
Fixed on the code-base, I don't when the change may be deployed to the web.

Your suggestion woudln't work, but it gave me the tip for where the problem was. :)

**Comment by oMarcinMazurek** [comment]
ok thank you :)
