### ISSUE TITLE
Compiler error

### ISSUE THREAD

**Issue by vmm2013** [JDaren/subtitleConverter#29]
System Ubuntu 14.04LTS , OpenJDK-7-jdk
[ERROR] /home/tladmin/subtitleConverter/src/main/java/IOClass.java:[51,31] variable pw might not have been initialized
[ERROR] /home/tladmin/subtitleConverter/src/main/java/IOClass.java:[106,32] variable br might not have been initialized

**Comment by flenoir** [comment]
Hi, i have the same error

 does anyone have solved this issue ?

**Comment by JDaren** [comment]
Yeah they have, but nobody pushed it, it's very simple to solve... I lost the project on my computer but I've just edited the file online. Can you confirm it is solved?
