### ISSUE TITLE
Exception trying to parse scc subtitle file

### ISSUE THREAD

**Issue by lynxlynxlynx** [JDaren/subtitleConverter#30]
> message For input string: "54;27"
> 
> description The server encountered an internal error that prevented it from fulfilling this request.
> 
> exception
> 
> java.lang.NumberFormatException: For input string: "54;27"
> 	java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
> 	java.lang.Integer.parseInt(Integer.java:492)
> 	java.lang.Integer.parseInt(Integer.java:527)
> 	sc.logic.Time.<init>(Time.java:39)
> 	sc.logic.FormatSCC.parseFile(FormatSCC.java:83)
> 	sc.servlet.ConverterServlet.doPost(ConverterServlet.java:122)
> 	javax.servlet.http.HttpServlet.service(HttpServlet.java:647)
> 	javax.servlet.http.HttpServlet.service(HttpServlet.java:728)

I don't have a way of viewing that file (that I know of), but it supposedly isn't damaged. Could this be a syntax incompatibility? I can send you the file, but the author doesn't want it to be publicly available.

**Comment by JDaren** [comment]
hmmm... that ';' between the numbers should probably be something else. If you want better help don't hesitate to contact me at my personal email, you can find it at subtitleconverter.net

**Comment by lynxlynxlynx** [comment]
I've got the file in a usable format, so this was more of a heads up.
