### ISSUE TITLE
Caption at zeroth index is skipped in an srt file

### ISSUE THREAD

**Issue by miankhalid** [JDaren/subtitleConverter#35]
In my project, we have srt files that look like below:

````
0
00:00:00,840 --> 00:00:02,090
This is line # 1

1
00:00:02,090 --> 00:00:03,530
This is line # 2

2
00:00:03,530 --> 00:00:05,210
This is line # 3
````

`This is line # 1` always gets skipped after parsing. Is this by design to skip the zeroth index caption?

**Comment by ethanhart** [comment]
The SubRip (srt) format uses a starting index of 1 by convention. https://media.readthedocs.org/pdf/srt/latest/srt.pdf

**Comment by miankhalid** [comment]
> The SubRip (srt) format uses a starting index of 1 by convention. 

Its implicitly mentioned in the doc you referenced i.e. all the `start_index` vars have value = 1, but it isn't explicitly mentioned that the starting index can't be some other number or should always be 1.

p.s. I did some research myself too, but couldn't find a solid reference that dictates the starting index to be always 1.

**Comment by ethanhart** [comment]
You're right- I never found "official" documentation indicating this, but there are a few libraries out there (e.g. pysrt) and other ways of generating SRTs (Youtube captions) and all follow the convention that the starting index is 1.

**Comment by miankhalid** [comment]
Gotcha!
My project had srt files starting index from 0, so, I modified the library to serve my case.

I can push the changes upstream in a PR, if you want?

**Comment by miankhalid** [comment]
Here's the jar that I made for my project with the said change: [subtitleConvert-1.0.2.jar.zip](https://github.com/JDaren/subtitleConverter/files/1575142/subtitleConvert-1.0.2.jar.zip)

Here's my project where this jar can be seen in action:
https://github.com/edx/edx-app-android/blob/47ec278e5b81561281fa4da404da1dcc41086a62/OpenEdXMobile/libs/subtitleConvert-1.0.2.jar
